export const CREATE_CONTACT_LOADING = "REGISTER_LOADING";

export const CREATE_CONTACT_SUCCESS = "REGISTER_SUCCESS";

export const CREATE_CONTACT_ERROR = "REGISTER_ERRROR";

export const CLEAR_CREATE_CONTACT_STATE = 'CLEAR_REGISTER_STATE'; 
 
