export const CREATE_CONTACT_LOADING = "REGISTER_LOADING";

export const CREATE_CONTACT_SUCCESS = "REGISTER_SUCCESS";

export const CREATE_CONTACT_ERROR = "REGISTER_ERRROR";

export const CLEAR_CREATE_CONTACT_STATE = 'CLEAR_REGISTER_STATE'; 

export const GET_CONTACTS_LOADING = "GET_CONTACTS_LOADING";

export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";

export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR";

export const CLEAR_GET_CONTACT_STATE = 'CLEAR_GET_CONTACT_STATE'; 
 
